version: '3.8'

#we need this docker compose file to define and manage multi container applications in a single YAML file
#this makes it easier to coordinate multiple services/replicate application environment

service:
  database:
  image: mysql
  volumes:
    - ./data/:docker-entrypoint-initdb.d/
  environment:
    - MYSQL_ROOT_PASSWORD=root 
    - MYSQL_USER=user 
    - MYSQL_PASSWORD=password 
    - MYSQL_DATABASE=world
  ports:
    - 3306:3306
  
webserver:
  buid: ./src 
  depends_on:
    - databse 
  restart: on-failure
  environment:
    - DATABASE_HOST=database 
  ports:
    - 3000:3000